An error occurred while executing the following cell:
------------------
try:
    from dynamax.hmm.demos.casino_hmm import make_model_and_data, plot_results, plot_inference
except ModuleNotFoundError:
    %pip install -qq dynamax
    from dynamax.hmm.demos.casino_hmm import make_model_and_data, plot_results, plot_inference
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3396/2489344644.py in <module>
      1 try:
----> 2     from dynamax.hmm.demos.casino_hmm import make_model_and_data, plot_results, plot_inference
      3 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'dynamax'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3396/2489344644.py in <module>
      3 except ModuleNotFoundError:
      4     get_ipython().run_line_magic('pip', 'install -qq dynamax')
----> 5     from dynamax.hmm.demos.casino_hmm import make_model_and_data, plot_results, plot_inference

ModuleNotFoundError: No module named 'dynamax'
ModuleNotFoundError: No module named 'dynamax'
